version: '3.8'

services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hoanglam1699
      MYSQL_DATABASE: interview
      MYSQL_USER: lam
      MYSQL_PASSWORD: hoanglam1699
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8.0-M04
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: