server:
  port: 8080
  servlet:
    context-path: /demo/api/v1

spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3309/interview?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379